#!/usr/bin/env php
<?php
if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

use Symfony\Component\Console\Application;
use WordPressGitInstaller\Console\NewCommand;

$app = new Application('WordPress Git Installer', '1.0');
$app->add(new NewCommand);

$app->run();
